import {app, BrowserWindow, globalShortcut, ipcMain} from 'electron';
import PersonaService from './service/persona.service';
import ChatIndexService from './service/chat-index.service';
import ChatService, {ChatMessage} from './service/chat.service';
import NewChatService from './service/new-chat.service';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: any;
let personaService: any;
let index: any;
let chat: any;
let newChat: NewChatService;
let mainService: any;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 768,
    width: 1280,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  //mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.on('submit-prompt', (event, arg) => {
  // Handle the message here, e.g., call a function with the provided arguments
  console.log(arg);

});

app.whenReady().then(() => {
  /*
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          'img-src https://oaidalleapiprodscus.blob.core.windows.net/ file:',
        ],
      },
    });
  });

   */

  personaService = new PersonaService();
  index = new ChatIndexService();
  chat = new ChatService();
  newChat = new NewChatService();

  personaService.readOrCreatePersona();

  chat.setPersona(personaService.getDefaultPersona());

  mainWindow.webContents.on('dom-ready', () => {
    //mainService.addAllHistory(index.index);
    //mainService.addConfigurationPanel(personaService.persona);
  });

  ipcMain.on('set-system', (event, name) => {
    chat.setPersona(personaService.getPersonaByName(name));
  });

  ipcMain.on('load-index', (event) => {
    const loadedIndex = index.read();
    mainWindow.webContents.send('index-load-reply', loadedIndex);
  });

  ipcMain.on('submit-prompt', (event, prompt: string) => {
    newChat.preProcess(prompt).then((preProcessedUserMessage: ChatMessage) => {

      return newChat.submit(preProcessedUserMessage, []);
    }).then((processed: unknown) => {
      console.log('Processed', processed);
      mainWindow.webContents.send('submit-prompt-reply', processed);
    }).catch((err: unknown) => {
      console.error('Chat error.', err);
    });

  });

  ipcMain.on('update-progress', (progress) => {
    mainService.updateWaitElement(progress);
  });

  ipcMain.on('new-session', (event) => {
    console.log('New session requested.');
    chat.new();
    mainService.newChatSession();
    mainService.addConfigurationPanel(personaService.persona);
  });

  ipcMain.on('load-chat-session', (event, sessionId) => {
    console.log('Load chat session requested.', sessionId);
    chat.readFromFile(sessionId);
    mainService.replaceChatSession(chat);
  });

  const ret = globalShortcut.register('CommandOrControl+Shift+I', () => {
    console.log('DevTools toggled');
    //mainWindow.webContents.toggleDevTools();
  });

  if (!ret) {
    console.log('registration failed');
  }

});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
