const USER_DATA_DIRECTORY = '.aitool';
const CHAT_DATA_DIRECTORY = USER_DATA_DIRECTORY + '/chat';
const PERSONA_DIRECTORY = USER_DATA_DIRECTORY + '/persona';

export {USER_DATA_DIRECTORY, CHAT_DATA_DIRECTORY, PERSONA_DIRECTORY};
